### PR TITLE
Create usrCostumer Table

### PR DESCRIPTION
**Pull request by mohammadpirzadeh**
usrCostumer Table Added

### CODE REVIEW

**Review by itafra-net — APPROVED** [review]

**Comment by mohammadpirzadeh** [comment]
usrCostumer

**Comment by vahid-pezeshki** [comment]
Fix this bug BOSS!

**Comment by mohammadpirzadeh** [comment]
trust

**Review by mohammadpirzadeh — COMMENTED** [review]
trust

**Pull request closed without merging**
